In [5]:
from pathlib import Path
import pandas as pd

SHOPEE_DIR = Path(
    "/kaggle/input/datasets/trnquangtriu/10dataset/Shopee Rebrowser"
)

parquet_files = sorted(SHOPEE_DIR.glob("*.parquet"))

print("Số file Parquet:", len(parquet_files))

if not parquet_files:
    raise FileNotFoundError(
        f"Không tìm thấy file Parquet trong {SHOPEE_DIR}"
    )

file_info = pd.DataFrame([
    {
        "filename": p.name,
        "size_mb": round(p.stat().st_size / 1024**2, 2)
    }
    for p in parquet_files
])

display(file_info)

print(
    "Tổng dung lượng:",
    round(file_info["size_mb"].sum(), 2),
    "MB"
)

Số file Parquet: 30

              filename  size_mb
0   2026-08-12.parquet     0.60
1   2026-08-13.parquet     0.60
2   2026-08-14.parquet     1.04
3   2026-08-15.parquet     0.68
4   2026-08-16.parquet     0.55
5   2026-08-17.parquet     0.58
6   2026-08-18.parquet     0.56
7   2026-08-19.parquet     0.74
8   2026-08-20.parquet     0.50
9   2026-08-21.parquet     0.50
10  2026-08-22.parquet     0.78
11  2026-08-23.parquet     0.65
12  2026-08-24.parquet     0.79
13  2026-08-25.parquet     0.83
14  2026-08-26.parquet     0.79
15  2026-08-27.parquet     0.77
16  2026-08-28.parquet     0.78
17  2026-08-29.parquet     0.82
18  2026-08-30.parquet     0.82
19  2026-08-31.parquet     0.77
20  2026-09-01.parquet     0.56
21  2026-09-02.parquet     0.66
22  2026-09-03.parquet     0.74
23  2026-09-04.parquet     0.56
24  2026-09-05.parquet     0.60
25  2026-09-06.parquet     0.67
26  2026-09-07.parquet     0.70
27  2026-09-08.parquet     0.71
28  2026-09-09.parquet     0.67
29  2026-09-10.parquet     0.82

Tổng dung lượng: 20.84 MB

In [8]:
from pathlib import Path
import pandas as pd

# 1. Đường dẫn dataset Shopee
SHOPEE_DIR = Path(
    "/kaggle/input/datasets/trnquangtriu/10dataset/Shopee Rebrowser"
)

# 2. Tìm các file Parquet
parquet_files = sorted(SHOPEE_DIR.glob("*.parquet"))

if not parquet_files:
    raise FileNotFoundError(
        f"Không tìm thấy file Parquet trong: {SHOPEE_DIR}"
    )

# 3. Đọc một file mẫu
sample_file = parquet_files[0]

print("Đang đọc:", sample_file.name)

shopee_sample = pd.read_parquet(sample_file)

print("SHAPE:", shopee_sample.shape)

# 4. Tìm các cột quan trọng
keywords = [
    "item",
    "shop",
    "title",
    "name",
    "description",
    "price",
    "currency",
    "rating",
    "review",
    "comment",
    "url",
    "link",
    "category",
    "brand",
    "country",
    "region"
]

important_cols = [
    col for col in shopee_sample.columns
    if any(
        key in col.lower()
        for key in keywords
    )
]

print("\nCÁC CỘT QUAN TRỌNG:")
print(important_cols)

print("\nDỮ LIỆU MẪU:")
if important_cols:
    display(shopee_sample[important_cols].head(5).T)
else:
    print("Không tìm thấy cột khớp với danh sách từ khóa.")

print("\nTOÀN BỘ CỘT:")
print(shopee_sample.columns.tolist())

Đang đọc: 2026-08-12.parquet
SHAPE: (1000, 52)

CÁC CỘT QUAN TRỌNG:
['itemId', 'shopId', 'title', 'description', 'brand', 'brandId', 'currency', 'price', 'priceMin', 'priceMax', 'priceBeforeDiscount', 'priceMinBeforeDiscount', 'priceMaxBeforeDiscount', 'ratingAvg', 'ratingCount', 'commentCount', 'shopLocation', 'isServiceByShopee', 'shopName', 'shopRating', 'shopResponseRate', 'shopResponseTime', 'shopFollowerCount', 'shopItemCount', 'shopCreatedAt', 'isOfficialShop', 'shopRatingGood', 'shopRatingNormal', 'shopRatingBad', 'isShopeeVerified', 'shopDetailedLocation', 'productUrl']

DỮ LIỆU MẪU:

,0,1,2,3,4
itemId,28427988776,6456905708,12325267064,50353923140,44054232220
shopId,11666367,37000019,3137618,92008769,45018579
title,暴富賣場❗壁掛 公仔展示盒 公仔收納盒公仔盒 泡泡瑪特 盲盒展示盒 公仔展示櫃 展示櫃 壓剋...,雙拉鍊加厚包中包 收納袋（顏色隨機）,幫寶適拉拉褲L117片,上誼 倒立的兔子 大醬童書專賣店,國農保久乳 台農保久乳 農會調味乳 24入/箱 牛奶 牛乳 原味 草莓 麥芽 果汁 巧克力 ...
description,暴富賣場❗壁掛 公仔展示盒 公仔收納盒公仔盒 泡泡瑪特 盲盒展示盒 公仔展示櫃 展示櫃 壓剋...,#d廠 #預購款\n#雙拉鍊加厚包中包 （顏色隨機）\n#雙拉鍊 #加厚包中包 #收納袋 #...,新舊版混出貨\n幫寶適拉拉褲L117片\n一箱下單一次\n多箱要分開下單\n,大醬童書專賣店\n\n作者： 寶濫 \n原文作者： 보람\n譯者： 葉雨純\n繪者： 寶...,宅配通、新竹物流一單最多48罐\n\n此款為玻璃，夏天可冷藏、冬天可加熱飲用\n\n商品皆新...
brand,None,自有品牌,None,None,None
brandId,NaN,NaN,1146869.0,1081547.0,1084912.0
currency,TWD,TWD,TWD,TWD,TWD
price,[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM]
priceMin,28000000,5500000,100000000,23000000,49900000
priceMax,28000000,5500000,100000000,23000000,57000000
priceBeforeDiscount,[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM]
priceMinBeforeDiscount,[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM]
priceMaxBeforeDiscount,[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM]
ratingAvg,5.0,5.0,5.0,5.0,5.0
ratingCount,1.0,1.0,2.0,3.0,2.0
commentCount,1,1,2,3,2
shopLocation,None,None,None,None,None
isServiceByShopee,False,False,False,False,False
shopName,下單必暴富嚴選商品📣📣【滿129台幣出貨 不含運費】,LAGO123,jumbojiang,大醬童書專賣店,國農、台農各式保久乳品批發零售
shopRating,4.8433,4.951303,5.0,4.985963,4.974942
shopResponseRate,90.0,95.0,82.0,100.0,91.0
shopResponseTime,8842.0,6898000.0,9189.0,3580.0,10547.0
shopFollowerCount,2191.0,296.0,15.0,11273.0,1265.0
shopItemCount,4281.0,1146.0,16.0,807.0,56.0
shopCreatedAt,2016-10-29 15:44:03+00:00,2017-10-02 07:00:15+00:00,2016-02-03 03:37:38+00:00,2018-09-22 06:14:26+00:00,2017-11-25 17:14:28+00:00
isOfficialShop,False,False,False,False,False
shopRatingGood,19131.0,909.0,85.0,71466.0,2945.0
shopRatingNormal,670.0,7.0,0.0,86.0,14.0
shopRatingBad,189.0,1.0,0.0,22.0,3.0
isShopeeVerified,False,False,False,True,False
shopDetailedLocation,None,None,None,None,None
productUrl,[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM],[PREMIUM]

TOÀN BỘ CỘT:
['_primaryKey', '_firstSeenAt', '_lastSeenAt', 'itemId', 'shopId', 'title', 'description', 'status', 'condition', 'catId', 'categories', 'brand', 'brandId', 'currency', 'price', 'priceMin', 'priceMax', 'priceBeforeDiscount', 'priceMinBeforeDiscount', 'priceMaxBeforeDiscount', 'discount', 'ratingAvg', 'ratingCount', 'commentCount', 'likedCount', 'shopLocation', 'isAdult', 'isPreOrder', 'estimatedDays', 'isFreeShipping', 'isServiceByShopee', 'images', 'models', 'createdAt', 'shopName', 'shopRating', 'shopResponseRate', 'shopResponseTime', 'shopFollowerCount', 'shopItemCount', 'shopCreatedAt', 'isOfficialShop', 'shopRatingGood', 'shopRatingNormal', 'shopRatingBad', 'isShopeeVerified', 'shopDetailedLocation', 'isIndividualSeller', 'isMart', 'shippingFeeMin', 'modelsCount', 'productUrl']

In [9]:
from pathlib import Path
import pandas as pd
import numpy as np

SHOPEE_DIR = Path(
    "/kaggle/input/datasets/trnquangtriu/10dataset/Shopee Rebrowser"
)

parquet_files = sorted(SHOPEE_DIR.glob("*.parquet"))

if not parquet_files:
    raise FileNotFoundError(f"Không có Parquet tại {SHOPEE_DIR}")

frames = []

for path in parquet_files:
    df = pd.read_parquet(path)
    df["source_file"] = path.name
    frames.append(df)

shopee_raw = pd.concat(frames, ignore_index=True)

print("SỐ FILE:", len(parquet_files))
print("TỔNG BẢN GHI:", len(shopee_raw))
print("SỐ CỘT:", len(shopee_raw.columns))

# Chuẩn hóa giá trị placeholder
PLACEHOLDERS = {
    "",
    "[PREMIUM]",
    "NONE",
    "NULL",
    "NAN",
    "N/A"
}

def usable(series):
    s = series.astype("string").str.strip()
    return (
        s.notna()
        & ~s.str.upper().isin(PLACEHOLDERS)
    )

print("\n1. PHÂN BỐ ĐƠN VỊ TIỀN TỆ")
display(
    shopee_raw["currency"]
    .fillna("MISSING")
    .value_counts(dropna=False)
    .rename_axis("currency")
    .reset_index(name="rows")
)

print("\n2. SỐ BẢN GHI THEO FILE")
display(
    shopee_raw["source_file"]
    .value_counts()
    .sort_index()
    .rename_axis("file")
    .reset_index(name="rows")
)

print("\n3. KIỂM TRA TRÙNG SẢN PHẨM")

key_cols = ["shopId", "itemId"]

valid_key = shopee_raw[key_cols].notna().all(axis=1)

print("Bản ghi có đủ shopId + itemId:", valid_key.sum())

print(
    "Sản phẩm duy nhất:",
    shopee_raw.loc[valid_key, key_cols]
    .drop_duplicates()
    .shape[0]
)

print(
    "Bản ghi trùng shopId + itemId:",
    shopee_raw.loc[valid_key]
    .duplicated(key_cols)
    .sum()
)

print("\n4. CHẤT LƯỢNG CÁC TRƯỜNG")

quality_cols = [
    "title",
    "description",
    "brand",
    "currency",
    "price",
    "priceMin",
    "priceMax",
    "ratingAvg",
    "ratingCount",
    "commentCount",
    "productUrl",
    "shopLocation"
]

quality = []

for col in quality_cols:
    if col not in shopee_raw.columns:
        continue

    count = int(usable(shopee_raw[col]).sum())

    quality.append({
        "column": col,
        "usable_rows": count,
        "usable_pct": round(
            count / len(shopee_raw) * 100, 2
        )
    })

display(pd.DataFrame(quality))

print("\n5. KIỂM TRA URL THẬT")

url_text = shopee_raw["productUrl"].astype("string").str.strip()

valid_url = url_text.str.match(
    r"^https?://",
    case=False,
    na=False
)

print("URL có dạng http/https:", valid_url.sum())

display(
    shopee_raw.loc[
        valid_url,
        ["itemId", "shopId", "currency", "productUrl"]
    ].head(10)
)

print("\n6. KIỂM TRA PRICE MIN/MAX")

for col in ["priceMin", "priceMax"]:
    values = pd.to_numeric(
        shopee_raw[col],
        errors="coerce"
    )

    print(f"\n{col}")
    print(values.describe())

print("\n7. MẪU SẢN PHẨM THEO CURRENCY")

sample_cols = [
    "itemId",
    "shopId",
    "title",
    "currency",
    "price",
    "priceMin",
    "priceMax",
    "ratingAvg",
    "productUrl"
]

for currency, group in shopee_raw.groupby(
    "currency",
    dropna=False
):
    print("\nCURRENCY:", currency)
    display(group[sample_cols].head(3))

SỐ FILE: 30
TỔNG BẢN GHI: 28893
SỐ CỘT: 53

1. PHÂN BỐ ĐƠN VỊ TIỀN TỆ

  currency   rows
0      TWD  28893

2. SỐ BẢN GHI THEO FILE

                  file  rows
0   2026-08-12.parquet  1000
1   2026-08-13.parquet  1000
2   2026-08-14.parquet  1000
3   2026-08-15.parquet  1000
4   2026-08-16.parquet  1000
5   2026-08-17.parquet  1000
6   2026-08-18.parquet  1000
7   2026-08-19.parquet  1000
8   2026-08-20.parquet   583
9   2026-08-21.parquet   597
10  2026-08-22.parquet   920
11  2026-08-23.parquet   793
12  2026-08-24.parquet  1000
13  2026-08-25.parquet  1000
14  2026-08-26.parquet  1000
15  2026-08-27.parquet  1000
16  2026-08-28.parquet  1000
17  2026-08-29.parquet  1000
18  2026-08-30.parquet  1000
19  2026-08-31.parquet  1000
20  2026-09-01.parquet  1000
21  2026-09-02.parquet  1000
22  2026-09-03.parquet  1000
23  2026-09-04.parquet  1000
24  2026-09-05.parquet  1000
25  2026-09-06.parquet  1000
26  2026-09-07.parquet  1000
27  2026-09-08.parquet  1000
28  2026-09-09.parquet  1000
29  2026-09-10.parquet  1000

3. KIỂM TRA TRÙNG SẢN PHẨM
Bản ghi có đủ shopId + itemId: 28893
Sản phẩm duy nhất: 28893
Bản ghi trùng shopId + itemId: 0

4. CHẤT LƯỢNG CÁC TRƯỜNG

          column  usable_rows  usable_pct
0          title        28893      100.00
1    description        26798       92.75
2          brand         1811        6.27
3       currency        28893      100.00
4          price            0        0.00
5       priceMin        28893      100.00
6       priceMax        28893      100.00
7      ratingAvg        28893      100.00
8    ratingCount        25444       88.06
9   commentCount        28893      100.00
10    productUrl            0        0.00
11  shopLocation          333        1.15

5. KIỂM TRA URL THẬT
URL có dạng http/https: 0

Empty DataFrame
Columns: [itemId, shopId, currency, productUrl]
Index: []

6. KIỂM TRA PRICE MIN/MAX

priceMin
count    2.889300e+04
mean     1.285447e+08
std      6.876574e+08
min      1.000000e+05
25%      1.200000e+07
50%      2.990000e+07
75%      7.500000e+07
max      4.999990e+10
Name: priceMin, dtype: float64

priceMax
count    2.889300e+04
mean     1.676261e+08
std      9.060575e+08
min      1.000000e+05
25%      1.540000e+07
50%      3.750000e+07
75%      9.260000e+07
max      4.999990e+10
Name: priceMax, dtype: float64

7. MẪU SẢN PHẨM THEO CURRENCY

CURRENCY: TWD

,itemId,shopId,title,currency,price,priceMin,priceMax,ratingAvg,productUrl
0,28427988776,11666367,暴富賣場❗壁掛 公仔展示盒 公仔收納盒公仔盒 泡泡瑪特 盲盒展示盒 公仔展示櫃 展示櫃 壓剋...,TWD,[PREMIUM],28000000,28000000,5.0,[PREMIUM]
1,6456905708,37000019,雙拉鍊加厚包中包 收納袋（顏色隨機）,TWD,[PREMIUM],5500000,5500000,5.0,[PREMIUM]
2,12325267064,3137618,幫寶適拉拉褲L117片,TWD,[PREMIUM],100000000,100000000,5.0,[PREMIUM]

In [10]:
shopee_vnd = shopee_raw[
    shopee_raw["currency"]
    .astype("string")
    .str.upper()
    .eq("VND")
    .fillna(False)
].copy()

print("Số bản ghi VND:", len(shopee_vnd))

if len(shopee_vnd) > 0:

    print(
        "Số sản phẩm VND duy nhất:",
        shopee_vnd[
            ["shopId", "itemId"]
        ].drop_duplicates().shape[0]
    )

    display(
        shopee_vnd[
            [
                "itemId",
                "shopId",
                "title",
                "price",
                "priceMin",
                "priceMax",
                "ratingAvg",
                "ratingCount",
                "productUrl"
            ]
        ].head(10)
    )

else:
    print(
        "Không tìm thấy sản phẩm có currency = VND."
    )

Số bản ghi VND: 0
Không tìm thấy sản phẩm có currency = VND.

In [3]:
from pathlib import Path
import pandas as pd

# Tìm file sản phẩm của Step 9
files = list(
    Path("/kaggle/input").rglob("smart_products.parquet")
)

print("Tìm thấy:", len(files), "file")

for p in files:
    print(p)

if not files:
    raise FileNotFoundError(
        "Chưa tìm thấy smart_products.parquet. "
        "Hãy Add Input dataset Step 9."
    )

products = pd.read_parquet(files[0])

print("\nSHAPE:", products.shape)

print("\nCOLUMNS:")
print(products.columns.tolist())

print("\nAMAZON SAMPLE:")

source_col = next(
    (
        c for c in ["source", "platform"]
        if c in products.columns
    ),
    None
)

if source_col:
    amazon = products[
        products[source_col]
        .astype("string")
        .str.lower()
        .eq("amazon")
        .fillna(False)
    ].copy()

    print("Amazon products:", len(amazon))
    display(amazon.head(5).T)
else:
    print("Chưa xác định được cột nguồn dữ liệu.")

Tìm thấy: 1 file
/kaggle/input/datasets/trnquangtriu/dataset10b/smart_products.parquet

SHAPE: (164926, 47)

COLUMNS:
['product_id', 'product_name', 'category', 'subcategory', 'brand', 'price', 'currency', 'average_rating', 'review_count', 'sold_count', 'description', 'image_url', 'product_url', 'source', 'language', 'smart_product_name', 'smart_source', 'smart_currency', 'smart_price', 'smart_rating', 'smart_review_count', 'product_family', 'product_type', 'classification_method', 'matched_rule', 'has_valid_price', 'has_valid_currency', 'price_filter_eligible', 'quality_issue_count', 'quality_flags_json', 'product_family_v1', 'product_type_v1', 'classification_method_v1', 'matched_rule_v1', 'product_family_v2', 'product_type_v2', 'classification_method_v2', 'classification_reason_v2', 'etl_review_rows', 'etl_review_text_rows', 'etl_review_evidence_rows', 'has_review_evidence', 'product_url_available', 'product_type_candidate', 'product_family_candidate', 'classification_requires_validation', 'top5_evidence_ready']

AMAZON SAMPLE:
Amazon products: 121917

,0,1,2,3,4
product_id,amazon_B07PXGQC1Q,amazon_B07KTYJ769,amazon_B0BGNG1294,amazon_B08CLNX58K,amazon_B08WJSHSLC
product_name,Apple AirPods (2nd Generation) Wireless Earbud...,"Amazon Smart Plug, for home automation, Works ...","Amazon Basics HDMI Cable, 18Gbps High-Speed, 4...",SanDisk 32GB 2-Pack Ultra MicroSDHC UHS-I Memo...,Fire TV Stick (3rd Gen) with Alexa Voice Remot...
category,Apple Products,Amazon Devices,Home Audio & Theater,Computers,Amazon Devices
subcategory,None,None,None,None,None
brand,Apple,Amazon,Amazon Basics,SanDisk,Amazon
price,99.0,24.99,8.55,13.4,44.98
currency,USD,USD,USD,USD,USD
average_rating,4.7,4.7,4.7,4.7,4.7
review_count,585624,542825,507202,402800,379565
sold_count,NaN,NaN,NaN,NaN,NaN
description,None,None,None,None,None
image_url,None,None,None,None,None
product_url,NaN,NaN,NaN,NaN,NaN
source,amazon,amazon,amazon,amazon,amazon
language,en,en,en,en,en
smart_product_name,Apple AirPods (2nd Generation) Wireless Earbud...,"Amazon Smart Plug, for home automation, Works ...","Amazon Basics HDMI Cable, 18Gbps High-Speed, 4...",SanDisk 32GB 2-Pack Ultra MicroSDHC UHS-I Memo...,Fire TV Stick (3rd Gen) with Alexa Voice Remot...
smart_source,amazon,amazon,amazon,amazon,amazon
smart_currency,USD,USD,USD,USD,USD
smart_price,99.0,24.99,8.55,13.4,44.98
smart_rating,4.7,4.7,4.7,4.7,4.7
smart_review_count,585624.0,542825.0,507202.0,402800.0,379565.0
product_family,headphones,unknown,unknown,unknown,unknown
product_type,accessory,unknown,unknown,unknown,unknown
classification_method,keyword_rule,unclassified,unclassified,unclassified,unclassified
matched_rule,charging case,None,None,None,None
has_valid_price,True,True,True,True,True
has_valid_currency,True,True,True,True,True
price_filter_eligible,True,True,True,True,True
quality_issue_count,2,2,2,2,2
quality_flags_json,"[""missing_description"", ""missing_product_url""]","[""missing_description"", ""missing_product_url""]","[""missing_description"", ""missing_product_url""]","[""missing_description"", ""missing_product_url""]","[""missing_description"", ""missing_product_url""]"
product_family_v1,headphones,unknown,unknown,unknown,unknown
product_type_v1,accessory,unknown,unknown,unknown,unknown
classification_method_v1,keyword_rule,unclassified,unclassified,unclassified,unclassified
matched_rule_v1,charging case,None,None,None,None
product_family_v2,headphones,unknown,unknown,unknown,unknown
product_type_v2,needs_review,unknown,unknown,unknown,unknown
classification_method_v2,rule_based_v2,rule_based_v2,rule_based_v2,rule_based_v2,rule_based_v2
classification_reason_v2,conflicting_main_accessory_signals,no_matching_rule,no_matching_rule,no_matching_rule,no_matching_rule
etl_review_rows,704,1626,1170,515,797
etl_review_text_rows,704,1626,1169,515,797
etl_review_evidence_rows,704,1626,1169,515,797
has_review_evidence,True,True,True,True,True
product_url_available,False,False,False,False,False
product_type_candidate,needs_review,unknown,unknown,unknown,unknown
product_family_candidate,headphones,unknown,unknown,unknown,unknown
classification_requires_validation,True,True,True,True,True
top5_evidence_ready,True,True,True,True,True

In [4]:
import pandas as pd

# Nếu chưa chạy cell đọc Step 9
products = pd.read_parquet(
    "/kaggle/input/datasets/trnquangtriu/dataset10b/smart_products.parquet"
)

amazon = products[
    products["source"].astype("string").str.lower().eq("amazon").fillna(False)
].copy()

amazon["asin"] = (
    amazon["product_id"]
    .astype("string")
    .str.replace(r"^amazon_", "", regex=True)
    .str.strip()
    .str.upper()
)

amazon["valid_asin_format"] = amazon["asin"].str.fullmatch(
    r"[A-Z0-9]{10}",
    na=False
)

print("Amazon products:", len(amazon))
print("ASIN đúng định dạng:", amazon["valid_asin_format"].sum())
print("ASIN không đúng định dạng:", (~amazon["valid_asin_format"]).sum())
print("ASIN duy nhất:", amazon["asin"].nunique())
print("ASIN trùng:", amazon["asin"].duplicated().sum())

print("\nMẪU ASIN:")
display(
    amazon[
        ["product_id", "asin", "product_name", "price", "currency"]
    ].head(10)
)

print("\nASIN KHÔNG ĐÚNG ĐỊNH DẠNG:")
display(
    amazon.loc[
        ~amazon["valid_asin_format"],
        ["product_id", "asin", "product_name"]
    ].head(20)
)

Amazon products: 121917
ASIN đúng định dạng: 121917
ASIN không đúng định dạng: 0
ASIN duy nhất: 121917
ASIN trùng: 0

MẪU ASIN:

,product_id,asin,product_name,price,currency
0,amazon_B07PXGQC1Q,B07PXGQC1Q,Apple AirPods (2nd Generation) Wireless Earbud...,99.00,USD
1,amazon_B07KTYJ769,B07KTYJ769,"Amazon Smart Plug, for home automation, Works ...",24.99,USD
2,amazon_B0BGNG1294,B0BGNG1294,"Amazon Basics HDMI Cable, 18Gbps High-Speed, 4...",8.55,USD
3,amazon_B08CLNX58K,B08CLNX58K,SanDisk 32GB 2-Pack Ultra MicroSDHC UHS-I Memo...,13.40,USD
4,amazon_B08WJSHSLC,B08WJSHSLC,Fire TV Stick (3rd Gen) with Alexa Voice Remot...,44.98,USD
5,amazon_B07HZLHPKP,B07HZLHPKP,"Echo Show 5 (1st Gen, 2019 release) -- Smart d...",79.99,USD
6,amazon_B08XPWDSWW,B08XPWDSWW,TOZO T10 Bluetooth 5.3 Wireless Earbuds with W...,21.99,USD
7,amazon_B09V1FT19S,B09V1FT19S,SanDisk 256GB Extreme microSDXC UHS-I Memory C...,28.99,USD
8,amazon_B08F9ZCTCL,B08F9ZCTCL,"Fire TV Stick Lite, free and live TV, Alexa Vo...",19.99,USD
9,amazon_B0BSFT117F,B0BSFT117F,SanDisk Cruzer Blade 16GB USB 2.0 Flash Drive,5.38,USD

ASIN KHÔNG ĐÚNG ĐỊNH DẠNG:

Empty DataFrame
Columns: [product_id, asin, product_name]
Index: []

In [5]:
from pathlib import Path
import pandas as pd

OUTPUT_DIR = Path("/kaggle/working/step10")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Danh sách ASIN hợp lệ đã tạo ở cell trước
amazon_asins = (
    amazon.loc[
        amazon["valid_asin_format"],
        ["product_id", "asin", "product_name", "category"]
    ]
    .drop_duplicates("asin")
    .copy()
)

amazon_asins.to_parquet(
    OUTPUT_DIR / "amazon_asins_to_enrich.parquet",
    index=False
)

print("Đã lưu:", OUTPUT_DIR / "amazon_asins_to_enrich.parquet")
print("Số ASIN:", len(amazon_asins))

Đã lưu: /kaggle/working/step10/amazon_asins_to_enrich.parquet
Số ASIN: 121917

In [6]:
from pathlib import Path
import pandas as pd

STEP9_PATH = (
    "/kaggle/input/datasets/trnquangtriu/"
    "dataset10b/smart_products.parquet"
)

OUT_DIR = Path("/kaggle/working/step10")
OUT_DIR.mkdir(parents=True, exist_ok=True)

products = pd.read_parquet(STEP9_PATH)

amazon = products[
    products["source"]
    .astype("string")
    .str.lower()
    .eq("amazon")
    .fillna(False)
].copy()

amazon["asin"] = (
    amazon["product_id"]
    .astype("string")
    .str.replace(r"^amazon_", "", regex=True)
    .str.upper()
    .str.strip()
)

target_asins = set(amazon["asin"].dropna())

print("Tổng Amazon:", len(amazon))
print("ASIN cần đối chiếu:", len(target_asins))

Tổng Amazon: 121917
ASIN cần đối chiếu: 121917

In [7]:
!pip -q install -U datasets huggingface_hub

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 25.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 842.9/842.9 kB 45.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.3/125.3 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 107.3 MB/s eta 0:00:0000:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.

In [9]:
import datasets
import huggingface_hub
import pyarrow

print("datasets:", datasets.__version__)
print("huggingface_hub:", huggingface_hub.__version__)
print("pyarrow:", pyarrow.__version__)

from datasets import load_dataset

print("Import thành công!")

datasets: 5.0.1
huggingface_hub: 1.32.0
pyarrow: 24.0.0
Import thành công!

In [11]:
import requests
import json

META_URL = (
    "https://huggingface.co/datasets/"
    "McAuley-Lab/Amazon-Reviews-2023/"
    "resolve/main/raw/meta_categories/meta_Electronics.jsonl"
)

response = requests.get(
    META_URL,
    stream=True,
    timeout=(30, 120)
)

response.raise_for_status()

print("HTTP STATUS:", response.status_code)
print("CONTENT TYPE:", response.headers.get("Content-Type"))

try:
    for i, line in enumerate(response.iter_lines()):

        if not line:
            continue

        item = json.loads(line)

        print(f"\n===== METADATA {i + 1} =====")
        print("COLUMNS:", list(item.keys()))

        for key in [
            "parent_asin",
            "title",
            "description",
            "features",
            "categories",
            "price"
        ]:
            print(
                f"{key}: "
                f"{str(item.get(key))[:300]}"
            )

        if i >= 2:
            break

finally:
    response.close()

HTTP STATUS: 200
CONTENT TYPE: application/octet-stream

===== METADATA 1 =====
COLUMNS: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together']
parent_asin: B00MCW7G9M
title: FS-1051 FATSHARK TELEPORTER V3 HEADSET
description: ['Teleporter V3 The “Teleporter V3” kit sets a new level of value in the FPV world with Fat Shark renowned performance and quality. The fun of FPV is experienced firsthand through the large screen FPV headset with integrated NexwaveRF receiver technology while simultaneously recording onboard HD foo
features: []
categories: ['Electronics', 'Television & Video', 'Video Glasses']
price: None

===== METADATA 2 =====
COLUMNS: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together']
parent_asin: B00YT6XQSE
title: Ce-H22B12-S1 4Kx2K Hdmi 4Port
description: ['HDMI In - HDMI Out']
features: ['UPC: 662774021904', 'Weight: 0.600 lbs']
categories: ['Electronics', 'Television & Video', 'Accessories', 'Cables', 'HDMI Cables']
price: None

===== METADATA 3 =====
COLUMNS: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together']
parent_asin: B07SM135LS
title: Digi-Tatoo Decal Skin Compatible With MacBook Pro 13 inch (Model A2338/ A2289/ A2251) - Protective and Decorative Full Body Laptop Skin Decal Sticker, Anti-Scratch Vinly Skin Sticker Wrap [Fresh Marble]
description: []
features: ['WARNING: Please IDENTIFY MODEL NUMBER on the bottom of your Macbook. Only fits for model A2338/ A2289/ A2251 (Macbook Pro 13" w/ Touch Bar, 2022/2020 release).', 'Extra Care Yet Not Bulky. Our skin is capable of protecting the surface of your Macbook from daily scratches, dust, oil, water and fing
categories: ['Electronics', 'Computers & Accessories', 'Laptop Accessories', 'Skins & Decals', 'Decals']
price: 19.99

In [12]:
import requests
import json
import pandas as pd
from tqdm.auto import tqdm

TEST_LIMIT = 50_000

matched_rows = []
matched_asins = set()

scanned = 0

with requests.get(
    META_URL,
    stream=True,
    timeout=(30, 120)
) as response:

    response.raise_for_status()

    for line in tqdm(
        response.iter_lines(),
        total=TEST_LIMIT,
        desc="Amazon metadata pilot"
    ):

        if not line:
            continue

        item = json.loads(line)
        scanned += 1

        asin = str(
            item.get("parent_asin") or ""
        ).strip().upper()

        if asin in target_asins:

            matched_asins.add(asin)

            matched_rows.append({
                "asin": asin,
                "meta_title": item.get("title"),
                "meta_description": item.get("description"),
                "meta_features": item.get("features"),
                "meta_categories": item.get("categories"),
                "meta_price": item.get("price"),
                "metadata_category": "Electronics"
            })

        if scanned >= TEST_LIMIT:
            break

matched_df = pd.DataFrame(matched_rows)

print("\n===== KẾT QUẢ =====")
print("Metadata đã đọc:", scanned)
print("ASIN khớp duy nhất:", len(matched_asins))

print(
    "Tỷ lệ khớp trên mẫu metadata:",
    round(
        len(matched_asins) / scanned * 100,
        2
    ) if scanned else 0,
    "%"
)

if not matched_df.empty:
    display(matched_df.head(5))

Amazon metadata pilot:   0%|          | 0/50000 [00:00<?, ?it/s]

===== KẾT QUẢ =====
Metadata đã đọc: 50000
ASIN khớp duy nhất: 8339
Tỷ lệ khớp trên mẫu metadata: 16.68 %

,asin,meta_title,meta_description,meta_features,meta_categories,meta_price,metadata_category
0,B07SM135LS,Digi-Tatoo Decal Skin Compatible With MacBook ...,[],[WARNING: Please IDENTIFY MODEL NUMBER on the ...,"[Electronics, Computers & Accessories, Laptop ...",19.99,Electronics
1,B089CNGZCW,NotoCity Compatible with Vivoactive 4 band 22m...,[],[☛NotoCity 22mm band is designed for Vivoactiv...,"[Electronics, Wearable Technology, Clips, Arm ...",9.99,Electronics
2,B07BJ7ZZL7,"QGHXO Band for Garmin Vivofit 4, Soft Silicone...","[Compatibility, Custom designed for your preci...",[Personalized Your Garmin Vivofit 4 Activity T...,"[Electronics, Wearable Technology, Arm & Wrist...",14.89,Electronics
3,B0822SL7JX,May Chen Compatible with MacBook Pro 16 inch C...,[May Chen High Quality Plastic Hard Shell Case...,[【 COMPATIBLE WITH 】 Designed to Fits Perfectl...,"[Electronics, Computers & Accessories, Laptop ...",26.99,Electronics
4,B09M7TH3YC,Wenlaty Case Compatible with iPad 9th /8th /7t...,[],[😊Designed for iPad 9th/8th/7th Generation: Pr...,"[Electronics, Computers & Accessories, Tablet ...",19.99,Electronics

In [13]:
import requests
import json
import pandas as pd
from pathlib import Path
from tqdm.auto import tqdm

OUT_DIR = Path("/kaggle/working/step10")
OUT_DIR.mkdir(parents=True, exist_ok=True)

def normalize_text(value):
    if value is None:
        return ""

    if isinstance(value, list):
        return "\n".join(
            str(x).strip()
            for x in value
            if x is not None and str(x).strip()
        )

    return str(value).strip()


matched_rows = []
matched_asins = set()
scanned = 0

with requests.get(
    META_URL,
    stream=True,
    timeout=(30, 180)
) as response:

    response.raise_for_status()

    for line in tqdm(
        response.iter_lines(),
        desc="Scanning Electronics metadata"
    ):

        if not line:
            continue

        item = json.loads(line)
        scanned += 1

        asin = str(
            item.get("parent_asin") or ""
        ).strip().upper()

        if asin not in target_asins:
            continue

        matched_asins.add(asin)

        matched_rows.append({
            "asin": asin,
            "meta_title": normalize_text(
                item.get("title")
            ),
            "meta_description": normalize_text(
                item.get("description")
            ),
            "meta_features": normalize_text(
                item.get("features")
            ),
            "meta_categories": normalize_text(
                item.get("categories")
            ),
            "meta_main_category": normalize_text(
                item.get("main_category")
            ),
            "meta_store": normalize_text(
                item.get("store")
            ),
            "metadata_source": "Amazon Reviews 2023",
            "metadata_category": "Electronics"
        })

metadata_electronics = pd.DataFrame(matched_rows)

# Chỉ giữ một metadata cho mỗi ASIN.
# Nếu có nhiều bản ghi, ưu tiên bản có nội dung đầy đủ hơn.
if not metadata_electronics.empty:

    text_cols = [
        "meta_description",
        "meta_features",
        "meta_categories"
    ]

    metadata_electronics["content_score"] = sum(
        metadata_electronics[c].str.len().fillna(0)
        for c in text_cols
    )

    metadata_electronics = (
        metadata_electronics
        .sort_values(
            "content_score",
            ascending=False
        )
        .drop_duplicates(
            "asin",
            keep="first"
        )
        .drop(
            columns="content_score"
        )
        .reset_index(drop=True)
    )

metadata_electronics.to_parquet(
    OUT_DIR / "amazon_metadata_electronics_matched.parquet",
    index=False
)

print("\n===== KẾT QUẢ =====")
print("Metadata đã quét:", scanned)
print("ASIN khớp duy nhất:", len(metadata_electronics))

print(
    "Tỷ lệ bao phủ Amazon Step 9:",
    round(
        len(metadata_electronics)
        / len(target_asins) * 100,
        2
    ),
    "%"
)

if not metadata_electronics.empty:

    for col in [
        "meta_description",
        "meta_features",
        "meta_categories"
    ]:
        print(
            col,
            "có dữ liệu:",
            metadata_electronics[col]
            .str.strip()
            .ne("")
            .sum()
        )

    display(metadata_electronics.head(5))

Scanning Electronics metadata: 0it [00:00, ?it/s]

===== KẾT QUẢ =====
Metadata đã quét: 1610012
ASIN khớp duy nhất: 121917
Tỷ lệ bao phủ Amazon Step 9: 100.0 %
meta_description có dữ liệu: 67128
meta_features có dữ liệu: 117858
meta_categories có dữ liệu: 118831

,asin,meta_title,meta_description,meta_features,meta_categories,meta_main_category,meta_store,metadata_source,metadata_category
0,B001TK3FXY,Kodak EasyShare Z1485 14MP Digital Camera with...,From the Manufacturer\nSay hello to high resol...,This refurbished product is tested and certifi...,Electronics\nCamera & Photo\nDigital Cameras\n...,Camera & Photo,KODAK,Amazon Reviews 2023,Electronics
1,B000DZDTKU,Canon EOS 30D 8.2MP Digital SLR Camera (Body O...,Product Description\nEOS 30D_Perfection Refine...,2.5-inch LCD display\n8.2-megapixel CCD captur...,Electronics\nCamera & Photo\nDigital Cameras\n...,Camera & Photo,Canon,Amazon Reviews 2023,Electronics
2,B0007N3JA8,Kodak Easyshare Z740 5 MP Digital Camera with ...,Product Description\nGet up close to your imag...,5.0 MP resolution captures enough detail for p...,Electronics\nCamera & Photo\nDigital Cameras\n...,Camera & Photo,KODAK,Amazon Reviews 2023,Electronics
3,B0031RGGE8,Kodak Easyshare M550 12 MP Digital Camera with...,Product Description\nThe Kodak EasyShare M550 ...,12-megapixel resolution for stunning prints up...,Electronics\nCamera & Photo\nDigital Cameras\n...,Camera & Photo,KODAK,Amazon Reviews 2023,Electronics
4,B00C3R14J4,Canon VIXIA HF G30 HD Camcorder with HD CMOS Pro,Product Description\nVIXIA HF G30_The flagship...,Newly designed Genuine Canon 20x HD Video Lens...,Electronics\nCamera & Photo\nVideo\nCamcorders,Camera & Photo,Canon,Amazon Reviews 2023,Electronics

In [15]:
check_df = amazon[
    ["asin", "product_name", "category"]
].merge(
    metadata_electronics[
        [
            "asin",
            "meta_title",
            "meta_description",
            "meta_features",
            "meta_categories"
        ]
    ],
    on="asin",
    how="inner",
    validate="one_to_one"
)

print("Số sản phẩm khớp:", len(check_df))

display(
    check_df[
        [
            "asin",
            "product_name",
            "meta_title",
            "category",
            "meta_categories"
        ]
    ].sample(
        min(20, len(check_df)),
        random_state=42
    )
)

Số sản phẩm khớp: 121917

,asin,product_name,meta_title,category,meta_categories
44548,B000NWG3S8,Scosche Select 2002 to 2020 Lexus & Toyota Veh...,Scosche Select 2002 to 2020 Lexus & Toyota Veh...,Car Electronics,Car & Vehicle Electronics\nVehicle Electronics...
19827,B07VG6Z9TF,45W 20V 2.25A Laptop Charger for Lenovo Ideapa...,45W 20V 2.25A Laptop Charger for Lenovo Ideapa...,All Electronics,Electronics\nComputers & Accessories\nLaptop A...
3903,B085RJ1T8T,KabelDirekt – Banana Plugs – 5 Pairs (for Spea...,KabelDirekt – Banana Plugs – 5 Pairs (for Spea...,All Electronics,Electronics\nHome Audio\nHome Audio Accessorie...
107248,B00LJZQHMA,Adesso Imouse G1 - Illuminated Desktop Mouse,Adesso Imouse G1 - Illuminated Desktop Mouse,Computers,Electronics\nComputers & Accessories\nComputer...
40549,B00OBP9N2G,Snugg Apple iPad Air 2 Case - Leather Smart Co...,Snugg Apple iPad Air 2 Case - Leather Smart Co...,Computers,Electronics\nComputers & Accessories\nTablet A...
81625,B00DHHQSB8,Stellar Labs Fringe YAGI Antenna UHF + VHF HIG...,Stellar Labs Fringe YAGI Antenna UHF + VHF HIG...,All Electronics,Electronics\nTelevision & Video\nAccessories\n...
62227,B0944C2PL9,KSK KAISHEK Case Compatible for MacBook Pro 16...,KSK KAISHEK Case Compatible for MacBook Pro 16...,Cell Phones & Accessories,Electronics\nComputers & Accessories\nLaptop A...
7336,B09R2DFFMP,"Vondior Portable Radio, Digital AM/FM Radio wi...","Vondior Portable Radio, Digital AM/FM Radio wi...",All Electronics,Electronics\nPortable Audio & Video\nRadios\nP...
66810,B0BM7F79TJ,Rapink Patch Panel 48 Port Cat6A with Inline K...,Rapink Patch Panel 48 Port Cat6A with Inline K...,Industrial & Scientific,Electronics\nComputers & Accessories\nComputer...
5464,B08HGR89QH,SEYMAC stock iPad 6th/5th Generation Case/Air ...,SEYMAC stock iPad 6th/5th Generation Case/Air ...,Computers,Electronics\nComputers & Accessories\nTablet A...
65315,B08R5PFJHM,VPFET HDMI Extender Over Single Cat5e/6 HDMI O...,VPFET HDMI Extender Over Single Cat5e/6 HDMI O...,Industrial & Scientific,Electronics\nTelevision & Video\nAccessories\n...
119380,B000U39UJE,Leviton 47605-PSB DC POWER SUPPLY FOR USE W/LE...,Leviton 47605-PSB DC POWER SUPPLY FOR USE W/LE...,Tools & Home Improvement,Electronics\nHome Audio\nHome Audio Accessorie...
7713,B09YR41P6L,Feelcare 10 Inch WiFi Digital Picture Frame - ...,Feelcare 10 Inch WiFi Digital Picture Frame - ...,Camera & Photo,Electronics\nCamera & Photo\nLighting & Studio...
96153,B08KWPD2GL,"U Evolve Wireless Headphones, Lux Memory Foam ...","U Evolve Wireless Headphones, Lux Memory Foam ...",All Electronics,"Electronics\nHeadphones, Earbuds & Accessories..."
44251,B07C1M42QK,AKWOX (Pack of 3) Tempered Glass Screen Protec...,AKWOX (Pack of 3) Tempered Glass Screen Protec...,Cell Phones & Accessories,Electronics\nCamera & Photo\nAccessories\nDigi...
39690,B0716W5C5V,Replacement Inline Mic Remote Volume Control A...,Replacement Inline Mic Remote Volume Control A...,All Electronics,"Electronics\nHeadphones, Earbuds & Accessories..."
59284,B008XT0B7M,AmerTac - Zenith TP1100ULA 100 FT 4 Wire Round...,AmerTac - Zenith TP1100ULA 100 FT 4 Wire Round...,All Electronics,Electronics\nAccessories & Supplies\nTelephone...
19183,B07J31M7PW,Ultimate Ears BOOM 2 Portable Waterproof & Sho...,Ultimate Ears BOOM 2 Portable Waterproof & Sho...,All Electronics,Electronics\nPortable Audio & Video\nPortable ...
46582,B016045NDI,"Electriduct 1/2"" Spiral Cable Wrap Polyethylen...","Electriduct 1/2"" Spiral Cable Wrap Polyethylen...",Tools & Home Improvement,Electronics\nAccessories & Supplies\nCord Mana...
72185,B09YPYYN1V,"CarlinKit 4.0 Wireless CarPlay Adapter, Wirele...","CarlinKit 4.0 Wireless CarPlay Adapter, Wirele...",All Electronics,Electronics\nCar & Vehicle Electronics\nCar El...

In [23]:
from pathlib import Path

print("===== TẤT CẢ FILE LIÊN QUAN STEP 9 =====")

for p in Path("/kaggle/input").rglob("*"):
    if p.is_file() and (
        "review" in p.name.lower()
        or "step9" in p.name.lower()
        or "smart" in p.name.lower()
    ):
        print(
            p,
            "|",
            round(p.stat().st_size / 1024**2, 2),
            "MB"
        )

print("\n===== FILE TRONG DATASET10B =====")

STEP9_DIR = Path(
    "/kaggle/input/datasets/trnquangtriu/dataset10b"
)

for p in STEP9_DIR.rglob("*"):
    if p.is_file():
        print(p.relative_to(STEP9_DIR))

===== TẤT CẢ FILE LIÊN QUAN STEP 9 =====
/kaggle/input/datasets/trnquangtriu/dataset10b/smart_products.parquet | 32.77 MB
/kaggle/input/datasets/trnquangtriu/dataset10c/smart_reviews.parquet | 269.27 MB

===== FILE TRONG DATASET10B =====
smart_products.parquet

In [25]:
from pathlib import Path
import pandas as pd

OUT_DIR = Path("/kaggle/working/step10")
OUT_DIR.mkdir(parents=True, exist_ok=True)

PRODUCTS_PATH = Path(
    "/kaggle/input/datasets/trnquangtriu/"
    "dataset10b/smart_products.parquet"
)

REVIEWS_PATH = Path(
    "/kaggle/input/datasets/trnquangtriu/"
    "dataset10c/smart_reviews.parquet"
)

METADATA_PATH = (
    OUT_DIR / "amazon_metadata_electronics_matched.parquet"
)

# Kiểm tra file tồn tại
for path in [
    PRODUCTS_PATH,
    REVIEWS_PATH,
    METADATA_PATH
]:
    if not path.exists():
        raise FileNotFoundError(f"Không tìm thấy: {path}")

# Đọc dữ liệu
products = pd.read_parquet(PRODUCTS_PATH)
reviews = pd.read_parquet(REVIEWS_PATH)
metadata = pd.read_parquet(METADATA_PATH)

print("===== DỮ LIỆU ĐẦU VÀO =====")
print("Step 9 products:", products.shape)
print("Step 9 reviews:", reviews.shape)
print("Amazon metadata:", metadata.shape)

# Kiểm tra số lượng
assert len(products) == 164_926
assert len(reviews) == 767_179
assert len(metadata) == 121_917

# Kiểm tra khóa
assert products["product_id"].is_unique
assert metadata["asin"].is_unique

print("\nĐã đọc dữ liệu thành công!")

===== DỮ LIỆU ĐẦU VÀO =====
Step 9 products: (164926, 47)
Step 9 reviews: (767179, 16)
Amazon metadata: (121917, 9)

Đã đọc dữ liệu thành công!

In [26]:
import pandas as pd

unified_products = products.copy()

unified_products["asin"] = pd.NA

amazon_mask = (
    unified_products["source"]
    .astype("string")
    .str.lower()
    .eq("amazon")
    .fillna(False)
)

unified_products.loc[amazon_mask, "asin"] = (
    unified_products.loc[amazon_mask, "product_id"]
    .astype("string")
    .str.replace(r"^amazon_", "", regex=True)
    .str.upper()
    .str.strip()
)

metadata_cols = [
    "asin",
    "meta_title",
    "meta_description",
    "meta_features",
    "meta_categories",
    "meta_main_category",
    "meta_store",
    "metadata_source",
    "metadata_category"
]

unified_products = unified_products.merge(
    metadata[metadata_cols],
    on="asin",
    how="left",
    validate="many_to_one"
)

# Chỉ điền description khi bản gốc thiếu
original_description = (
    unified_products["description"]
    .astype("string")
    .str.strip()
)

missing_description = (
    original_description.isna()
    | original_description.eq("")
    | original_description.str.lower().isin(
        ["none", "nan", "null"]
    )
).fillna(True)

new_description = (
    unified_products["meta_description"]
    .astype("string")
    .str.strip()
)

valid_new_description = (
    new_description.notna()
    & new_description.ne("")
).fillna(False)

fill_mask = missing_description & valid_new_description

unified_products.loc[
    fill_mask,
    "description"
] = unified_products.loc[
    fill_mask,
    "meta_description"
]

# Cột bổ sung phục vụ tìm kiếm và RAG
unified_products["product_features"] = (
    unified_products["meta_features"]
)

unified_products["category_path"] = (
    unified_products["meta_categories"]
)

unified_products["metadata_enriched"] = (
    unified_products["metadata_source"].notna()
)

unified_products["description_enriched"] = fill_mask

print("Tổng sản phẩm:", len(unified_products))
print(
    "Sản phẩm khớp metadata:",
    unified_products["metadata_enriched"].sum()
)
print(
    "Description được bổ sung:",
    unified_products["description_enriched"].sum()
)

assert len(unified_products) == len(products)

display(
    unified_products.loc[
        unified_products["description_enriched"],
        [
            "product_id",
            "product_name",
            "description",
            "product_features",
            "category_path"
        ]
    ].head(5)
)

Tổng sản phẩm: 164926
Sản phẩm khớp metadata: 121917
Description được bổ sung: 67128

,product_id,product_name,description,product_features,category_path
2,amazon_B0BGNG1294,"Amazon Basics HDMI Cable, 18Gbps High-Speed, 4...",Product Description\nAmazon Basics High-Speed ...,IN THE BOX: HDMI cable (A Male to A Male) for ...,Electronics\nTelevision & Video\nAccessories\n...
3,amazon_B08CLNX58K,SanDisk 32GB 2-Pack Ultra MicroSDHC UHS-I Memo...,Transfer speeds of up to 98MB/sec . Records Fu...,Speeds up to 98MB/sec | Up to 98MB/s read spee...,Electronics\nComputers & Accessories\nComputer...
7,amazon_B09V1FT19S,SanDisk 256GB Extreme microSDXC UHS-I Memory C...,With the SanDisk Extreme 256GB microSD UHS-I M...,Up to 160MB/s read speeds to save time transfe...,Electronics\nComputers & Accessories\nComputer...
9,amazon_B0BSFT117F,SanDisk Cruzer Blade 16GB USB 2.0 Flash Drive,Take your favorite files with you on the ultra...,Ultra-compact and portable contoured styling\n...,Electronics\nComputers & Accessories\nData Sto...
13,amazon_B073JWXGNT,SanDisk 32GB Ultra MicroSDHC UHS-I Memory Card...,SanDisk Ultra microSDXC and microSDHC cards ar...,"Ideal for Android smartphones and tablets, and...",Electronics\nComputers & Accessories\nComputer...

In [27]:
import pandas as pd

original = products.set_index("product_id")
updated = unified_products.set_index("product_id")

protected_cols = [
    "product_name",
    "price",
    "currency",
    "average_rating",
    "review_count",
    "smart_price",
    "smart_rating",
    "smart_review_count",
    "source"
]

print("===== KIỂM TRA CÁC CỘT GỐC =====")

for col in protected_cols:

    same = original[col].equals(
        updated.loc[original.index, col]
    )

    print(f"{col}: {'OK' if same else 'CHANGED'}")

    assert same, f"Cột {col} đã bị thay đổi!"

assert len(updated) == len(original)

assert updated.index.is_unique

print("\nTất cả kiểm tra thành công!")

===== KIỂM TRA CÁC CỘT GỐC =====
product_name: OK
price: OK
currency: OK
average_rating: OK
review_count: OK
smart_price: OK
smart_rating: OK
smart_review_count: OK
source: OK

Tất cả kiểm tra thành công!

In [28]:
import json

def available_text(series):

    s = series.astype("string").str.strip()

    return (
        s.notna()
        & s.ne("")
        & ~s.str.lower().isin(
            ["none", "nan", "null"]
        )
    ).fillna(False)


amazon_unified = unified_products[
    unified_products["source"]
    .astype("string")
    .str.lower()
    .eq("amazon")
    .fillna(False)
]

report = {
    "step": "step10_unified_ecommerce_dataset",

    "products_before": int(len(products)),
    "products_after": int(len(unified_products)),

    "reviews_before": int(len(reviews)),
    "reviews_after": int(len(reviews)),

    "amazon_products": int(len(amazon_unified)),

    "amazon_metadata_matched": int(
        amazon_unified["metadata_enriched"].sum()
    ),

    "amazon_description_available": int(
        available_text(
            amazon_unified["description"]
        ).sum()
    ),

    "amazon_features_available": int(
        available_text(
            amazon_unified["product_features"]
        ).sum()
    ),

    "amazon_category_path_available": int(
        available_text(
            amazon_unified["category_path"]
        ).sum()
    ),

    "shopee_rebrowser_integrated": False,

    "price_overwritten": False,

    "rating_overwritten": False,

    "reviews_modified": False,

    "embeddings_rebuilt": False,

    "faiss_rebuilt": False
}

print(json.dumps(
    report,
    indent=2,
    ensure_ascii=False
))

with open(
    OUT_DIR / "step10_enrichment_report.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        report,
        f,
        ensure_ascii=False,
        indent=2
    )

{
  "step": "step10_unified_ecommerce_dataset",
  "products_before": 164926,
  "products_after": 164926,
  "reviews_before": 767179,
  "reviews_after": 767179,
  "amazon_products": 121917,
  "amazon_metadata_matched": 121917,
  "amazon_description_available": 67127,
  "amazon_features_available": 117858,
  "amazon_category_path_available": 118831,
  "shopee_rebrowser_integrated": false,
  "price_overwritten": false,
  "rating_overwritten": false,
  "reviews_modified": false,
  "embeddings_rebuilt": false,
  "faiss_rebuilt": false
}

In [29]:
import pandas as pd

meta_has_description = (
    metadata["meta_description"]
    .astype("string")
    .str.strip()
    .notna()
    &
    metadata["meta_description"]
    .astype("string")
    .str.strip()
    .ne("")
).fillna(False)

meta_asins = set(
    metadata.loc[meta_has_description, "asin"]
)

amazon_after = unified_products[
    unified_products["source"]
    .astype("string")
    .str.lower()
    .eq("amazon")
    .fillna(False)
].copy()

final_description = (
    amazon_after["description"]
    .astype("string")
    .str.strip()
)

final_has_description = (
    final_description.notna()
    & final_description.ne("")
    & ~final_description.str.lower().isin(
        ["none", "nan", "null"]
    )
).fillna(False)

final_asins = set(
    amazon_after.loc[final_has_description, "asin"]
)

difference = meta_asins - final_asins

print("Metadata có description:", len(meta_asins))
print("Sau hợp nhất có description:", len(final_asins))
print("ASIN chênh lệch:", len(difference))

if difference:
    display(
        unified_products.loc[
            unified_products["asin"].isin(difference),
            [
                "asin",
                "product_name",
                "description",
                "meta_description"
            ]
        ]
    )

Metadata có description: 67128
Sau hợp nhất có description: 67127
ASIN chênh lệch: 1

,asin,product_name,description,meta_description
75924,B09528H4TX,(2 Pack) Stylus s Pen Nibs/Tips Replacement fo...,none,none

In [32]:
from pathlib import Path
import pandas as pd

OUT_DIR = Path("/kaggle/working/step10")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Kiểm tra biến còn trong phiên Kaggle
if "unified_products" not in globals():
    raise RuntimeError(
        "Không tìm thấy biến unified_products. "
        "Hãy chạy lại Cell 8 và Cell 9 trước."
    )

if "reviews" not in globals():
    raise RuntimeError(
        "Không tìm thấy biến reviews. "
        "Hãy chạy lại Cell 8 trước."
    )

if "metadata" not in globals():
    raise RuntimeError(
        "Không tìm thấy biến metadata. "
        "Hãy chạy lại Cell 8 trước."
    )

# Kiểm tra số lượng trước khi xuất
assert len(unified_products) == 164_926
assert len(reviews) == 767_179
assert len(metadata) == 121_917

# Xuất dữ liệu
unified_products.to_parquet(
    OUT_DIR / "unified_products.parquet",
    index=False
)

reviews.to_parquet(
    OUT_DIR / "unified_reviews.parquet",
    index=False
)

# Metadata đã được lưu ở Cell 6.
# Chỉ xuất lại nếu file chưa tồn tại.
metadata_path = (
    OUT_DIR / "amazon_metadata_electronics_matched.parquet"
)

if not metadata_path.exists():
    metadata.to_parquet(
        metadata_path,
        index=False
    )

print("===== ĐÃ XUẤT STEP 10 =====")

for p in OUT_DIR.iterdir():
    if p.is_file():
        print(
            p.name,
            "|",
            round(p.stat().st_size / 1024**2, 2),
            "MB"
        )

===== ĐÃ XUẤT STEP 10 =====
amazon_asins_to_enrich.parquet | 13.2 MB
step10_enrichment_report.json | 0.0 MB
unified_products.parquet | 232.08 MB
unified_reviews.parquet | 269.27 MB
amazon_metadata_electronics_matched.parquet | 102.81 MB

In [33]:
from pathlib import Path
import shutil

OUT_DIR = Path("/kaggle/working/step10")

required_files = [
    "unified_products.parquet",
    "unified_reviews.parquet",
    "amazon_metadata_electronics_matched.parquet",
    "step10_enrichment_report.json"
]

for filename in required_files:
    path = OUT_DIR / filename
    assert path.exists(), f"Thiếu file: {filename}"

ZIP_PATH = shutil.make_archive(
    "/kaggle/working/step10_final",
    "zip",
    root_dir=OUT_DIR
)

print("Đã đóng gói:", ZIP_PATH)

print("\n===== FILE OUTPUT =====")

for filename in required_files:
    path = OUT_DIR / filename

    print(
        filename,
        "|",
        round(path.stat().st_size / 1024**2, 2),
        "MB"
    )

Đã đóng gói: /kaggle/working/step10_final.zip

===== FILE OUTPUT =====
unified_products.parquet | 232.08 MB
unified_reviews.parquet | 269.27 MB
amazon_metadata_electronics_matched.parquet | 102.81 MB
step10_enrichment_report.json | 0.0 MB